<?php

/**
 * Andhra Pradesh Districts and Mandals
 * Source: Wikipedia List of mandals of Andhra Pradesh (2025 - 688 mandals across 28 districts)
 * District names aligned with AP_Districts_Final.json where applicable.
 */

return [
    'state' => 'Andhra Pradesh',

    'districts' => [
        'Alluri Sitharama Raju',
        'Anakapalli',
        'Ananthapuramu',
        'Annamayya',
        'Bapatla',
        'Chittoor',
        'Dr. B.R. Ambedkar Konaseema',
        'East Godavari',
        'Eluru',
        'Guntur',
        'Kakinada',
        'Krishna',
        'Kurnool',
        'Markapuram',
        'Nandyal',
        'NTR',
        'Palnadu',
        'Parvathipuram Manyam',
        'Polavaram',
        'Prakasam',
        'Sri Potti Sriramulu Nellore',
        'Sri Sathya Sai',
        'Srikakulam',
        'Tirupati',
        'Visakhapatnam',
        'Vizianagaram',
        'West Godavari',
        'YSR Kadapa',
    ],

    'mandals_by_district' => [
        'Alluri Sitharama Raju' => [
            'Ananthagiri', 'Araku Valley', 'Chintapalle', 'Dumbriguda', 'G. Madugula', 'Gudem Kotha Veedhi',
            'Hukumpeta', 'Koyyuru', 'Munchingi Puttu', 'Paderu', 'Peda Bayalu',
            'Addateegala', 'Devipatnam', 'Gangavaram', 'Gurthedu', 'Maredumilli', 'Rajavommangi',
            'Rampachodavaram', 'Y. Ramavaram',
        ],
        'Anakapalli' => [
            'Atchutapuram', 'Elamanchili', 'Kotauratla', 'Nakkapalle', 'Payakaraopeta', 'Rambilli',
            'Sarvasiddhi Rayavaram', 'Anakapalle', 'Butchayyapeta', 'Cheedikada', 'Chodavaram',
            'Devarapalli', 'K.Kotapadu', 'Kasimkota', 'Munagapaka', 'Paravada', 'Sabbavaram',
            'Golugonda', 'Madugula', 'Makavarapalem', 'Narsipatnam', 'Nathavaram', 'Ravikamatham', 'Rolugunta',
        ],
        'Ananthapuramu' => [
            'Anantapur', 'Atmakur', 'Bukkaraya Samudram', 'Garladinne', 'Kudair', 'Narpala',
            'Peddapappur', 'Putlur', 'Raptadu', 'Singanamala', 'Tadipatri', 'Yellanur',
            'Gooty', 'Guntakal', 'Pamidi', 'Peddavadugur', 'Uravakonda', 'Vajrakarur', 'Vidapanakal', 'Yadiki',
            'Beluguppa', 'Bommanahal', 'Brahmasamudram', 'D.Hirehal', 'Gummagatta', 'Kalyandurg',
            'Kambadur', 'Kanekal', 'Kundurpi', 'Rayadurg', 'Settur',
        ],
        'Annamayya' => [
            'Beerangi Kothakota', 'Chowdepalle', 'Kurabalakota', 'Madanapalle', 'Mulakalacheruvu',
            'Nimmanapalle', 'Peddamandyam', 'Peddathippasamudram', 'Punganur', 'Ramasamudram', 'Thamballapalle',
            'Gurramkonda', 'Kalakada', 'Kalikiri', 'Kambhamvaripalle', 'Pileru', 'Sodam', 'Somala', 'Vayalpad',
            'Chinnamandyam', 'Galiveedu', 'Lakkireddipalli', 'Ramapuram', 'Rayachoti', 'Sambepalli',
        ],
        'Bapatla' => [
            'Bapatla', 'Karlapalem', 'Martur', 'Parchur', 'Pittalavanipalem', 'Yeddanapudi',
            'Chinaganjam', 'Chirala', 'Inkollu', 'Karamchedu', 'Vetapalem',
            'Amruthalur', 'Bhattiprolu', 'Cherukupalle', 'Kolluru', 'Nagaram', 'Nizampatnam',
            'Repalle', 'Tsundur', 'Vemuru',
        ],
        'Chittoor' => [
            'Bangarupalem', 'Chittoor', 'Chittoor Urban', 'Gangadhara Nellore', 'Gudipala', 'Irala',
            'Penumuru', 'Pulicherla', 'Puthalapattu', 'Rompicherla', 'Sri Rangaraja Puram', 'Thavanampalle',
            'Vedurukuppam', 'Yadamarri', 'Kuppam', 'Ramakuppam', 'Santhipuram', 'Gudipalle',
            'Nagari', 'Nindra', 'Palasamudram', 'Vijayapuram', 'Karvetinagar',
            'Baireddipalle', 'Gangavaram', 'Palamaner', 'Peddapanjani', 'Venkatagirikota',
        ],
        'Dr. B.R. Ambedkar Konaseema' => [
            'Allavaram', 'Amalapuram', 'I. Polavaram', 'Katrenikona', 'Malikipuram', 'Mamidikuduru',
            'Mummidivaram', 'Razole', 'Sakhinetipalle', 'Uppalaguptam',
            'Ainavilli', 'Alamuru', 'Ambajipeta', 'Atreyapuram', 'Kothapeta', 'P. Gannavaram', 'Ravulapalem',
            'K. Gangavaram', 'Ramachandrapuram',
        ],
        'East Godavari' => [
            'Chagallu', 'Devarapalle', 'Gopalapuram', 'Kovvur', 'Nallajerla', 'Nidadavole',
            'Peravali', 'Tallapudi', 'Undrajavaram',
            'Anaparthi', 'Biccavolu', 'Gokavaram', 'Kadiam', 'Kapileswarapuram', 'Korukonda',
            'Mandapeta', 'Rajahmundry Urban', 'Rajahmundry Rural', 'Rajanagaram', 'Rangampeta',
            'Rayavaram', 'Seethanagaram',
        ],
        'Eluru' => [
            'Bhimadole', 'Denduluru', 'Eluru', 'Kaikalur', 'Kalidindi', 'Mandavalli', 'Mudinepalle',
            'Nidamarru', 'Pedapadu', 'Pedavegi', 'Unguturu',
            'Buttayagudem', 'Dwaraka Tirumala', 'Jangareddygudem', 'Jeelugu Milli', 'Kamavarapukota',
            'Koyyalagudem', 'Kukunoor', 'Polavaram', 'T. Narasapuram', 'Velairpadu',
            'Agiripalli', 'Chatrai', 'Chintalapudi', 'Lingapalem', 'Musunuru', 'Nuzvid',
        ],
        'Guntur' => [
            'Guntur East', 'Guntur West', 'Medikonduru', 'Pedakakani', 'Pedanandipadu', 'Phirangipuram',
            'Prathipadu', 'Tadikonda', 'Thullur', 'Vatticherukuru',
            'Chebrolu', 'Duggirala', 'Kakumanu', 'Kollipara', 'Mangalagiri', 'Ponnur', 'Tadepalle', 'Tenali',
        ],
        'Kakinada' => [
            'Gollaprolu', 'Kajuluru', 'Kakinada Rural', 'Kakinada Urban', 'Karapa', 'Kothapalle',
            'Pedapudi', 'Pithapuram', 'Thallarevu',
            'Gandepalle', 'Jaggampeta', 'Kirlampudi', 'Kotananduru', 'Peddapuram', 'Prathipadu',
            'Rowthulapudi', 'Samalkota', 'Sankhavaram', 'Thondangi', 'Tuni', 'Yeleswaram',
        ],
        'Krishna' => [
            'Bapulapadu', 'Gannavaram', 'Gudivada', 'Gudlavalleru', 'Nandivada', 'Pedaparupudi', 'Unguturu',
            'Avanigadda', 'Bantumilli', 'Challapalli', 'Ghantasala', 'Guduru', 'Koduru', 'Kruthivennu',
            'Machilipatnam', 'Mopidevi', 'Nagayalanka', 'Pedana',
            'Kankipadu', 'Movva', 'Pamarru', 'Pamidimukkala', 'Penamaluru', 'Thotlavalluru', 'Vuyyuru',
        ],
        'Kurnool' => [
            'Adoni Urban', 'Adoni Rural', 'Gonegandla', 'Holagunda', 'Kosigi', 'Kowthalam',
            'Mantralayam', 'Nandavaram', 'Pedda Kadubur', 'Yemmiganur',
            'C.Belagal', 'Gudur', 'Kallur', 'Kodumur', 'Kurnool Urban', 'Kurnool Rural',
            'Orvakal', 'Veldurthi',
            'Alur', 'Aspari', 'Chippagiri', 'Devanakonda', 'Halaharvi', 'Krishnagiri',
            'Maddikera East', 'Pattikonda', 'Tuggali',
        ],
        'Markapuram' => [
            'Chandra Sekhara Puram', 'Hanumanthuni Padu', 'Kanigiri', 'Pamur', 'Pedacherlo Palle', 'Veligandla',
            'Ardhaveedu', 'Bestawaripeta', 'Cumbum', 'Dornala', 'Giddalur', 'Konakanamitla', 'Komarolu',
            'Markapuram', 'Peda Araveedu', 'Pullalacheruvu', 'Podili', 'Racherla', 'Tarlupadu',
            'Tripuranthakam', 'Yerragondapalem',
        ],
        'Nandyal' => [
            'Atmakur', 'Bandi Atmakur', 'Jupadu Bungalow', 'Kothapalle', 'Midthuru', 'Nandikotkur',
            'Pagidyala', 'Pamulapadu', 'Srisailam', 'Velgodu',
            'Banaganapalle', 'Koilkuntla', 'Kolimigundla', 'Owk', 'Sanjamala',
            'Bethamcherla', 'Dhone', 'Peapally',
            'Allagadda', 'Chagalamarri', 'Dornipadu', 'Gadivemula', 'Gospadu', 'Mahanandi',
            'Nandyal Rural', 'Nandyal Urban', 'Panyam', 'Rudravaram', 'Sirivella', 'Uyyalawada',
        ],
        'NTR' => [
            'Chandarlapadu', 'Jaggayyapeta', 'Kanchikacherla', 'Nandigama', 'Penuganchiprolu', 'Vatsavai',
            'Veerullapadu', 'A. Konduru', 'Gampalagudem', 'Reddigudem', 'Tiruvuru', 'Vissannapeta',
            'G.Konduru', 'Ibrahimpatnam', 'Mylavaram', 'Vijayawada Rural', 'Vijayawada North',
            'Vijayawada Central', 'Vijayawada East', 'Vijayawada West',
        ],
        'Palnadu' => [
            'Dachepalle', 'Durgi', 'Gurazala', 'Karempudi', 'Macherla', 'Machavaram', 'Piduguralla',
            'Rentachintala', 'Veldurthi',
            'Bollapalle', 'Chilakaluripet', 'Edlapadu', 'Ipuru', 'Nadendla', 'Narasaraopet',
            'Nuzendla', 'Rompicherla', 'Savalyapuram', 'Vinukonda',
            'Amaravathi', 'Atchampet', 'Bellamkonda', 'Krosuru', 'Muppalla', 'Nekarikallu',
            'Pedakurapadu', 'Rajupalem', 'Sattenapalle',
        ],
        'Parvathipuram Manyam' => [
            'Bhamini', 'Gummalakshmipuram', 'Jiyyammavalasa', 'Kurupam', 'Palakonda', 'Seethampeta',
            'Veeraghattam',
            'Balijipeta', 'Garugubilli', 'Komarada', 'Makkuva', 'Pachipenta', 'Parvathipuram',
            'Salur', 'Seethanagaram',
        ],
        'Polavaram' => [
            'Chintur', 'Etapaka', 'Kunavaram', 'Vararamachandrapuram',
        ],
        'Prakasam' => [
            'Korisapadu', 'J. Panguluru', 'Addanki', 'Ballikurava', 'Santhamaguluru', 'Mundlamuru Ongole',
            'Thallur', 'Darsi', 'Donakonda Kanigiri', 'Kurichedu',
            'Gudluru', 'Kandukuru', 'Lingasamudram', 'Ulavapadu', 'Marripudi', 'Ponnaluru',
            'Voletivaripalem',
            'Chimakurthi', 'Kondapi', 'Kotha Patnam', 'Maddipadu', 'Naguluppalapadu',
            'Ongole Urban', 'Ongole Rural', 'Santhanuthala Padu', 'Singarayakonda', 'Tangutur', 'Zarugumilli',
        ],
        'Sri Potti Sriramulu Nellore' => [
            'Ananthasagaram', 'Anumasamudrampeta', 'Atmakur', 'Chejerla', 'Kaluvoya', 'Marripadu',
            'Sangam', 'Sitarampuramu', 'Udayagiri',
            'Gudur', 'Chillakur', 'Kota', 'Allur', 'Bogolu', 'Dagadarthi', 'Duttaluru', 'Jaladanki',
            'Kaligiri', 'Kavali', 'Kodavaluru', 'Vidavaluru', 'Vinjamuru',
            'Buchireddypalem', 'Indukurpet', 'Kovur', 'Manubolu', 'Muttukuru', 'Nellore Urban',
            'Nellore Rural', 'Podalakuru', 'Rapuru', 'Saidapuramu', 'Thotapalligudur', 'Venkatachalam',
        ],
        'Sri Sathya Sai' => [
            'Bathalapalle', 'Chennekothapalle', 'Dharmavaram', 'Kanaganapalle', 'Mudigubba',
            'Ramagiri', 'Tadimarri',
            'Gandlapenta', 'Kadiri', 'Lepakshi', 'Nallacheruvu', 'Nambulapulakunta', 'Tanakal',
            'Agali', 'Amarapuram', 'Gudibanda', 'Madakasira', 'Rolla',
            'Chilamathur', 'Gorantla', 'Hindupur', 'Parigi', 'Penukonda', 'Roddam', 'Somandepalle',
            'Talupula',
            'Amadagur', 'Bukkapatnam', 'Kothacheruvu', 'Nallamada', 'Obuladevaracheruvu', 'Puttaparthi',
        ],
        'Srikakulam' => [
            'Ichchapuram', 'Kanchili', 'Kaviti', 'Mandasa', 'Palasa', 'Sompeta', 'Vajrapukothuru',
            'Amadalavalasa', 'Burja', 'Etcherla', 'Ganguvarisigadam', 'Gara', 'Jalumuru', 'Laveru',
            'Narasannapeta', 'Polaki', 'Ponduru', 'Ranastalam', 'Sarubujjili', 'Srikakulam',
            'Hiramandalam', 'Kotabommali', 'Kothuru', 'Lakshminarsupeta', 'Meliaputti', 'Nandigam',
            'Pathapatnam', 'Santhabommali', 'Saravakota', 'Tekkali',
        ],
        'Tirupati' => [
            'Balayapalle', 'Dakkili', 'K. V. B. Puram', 'Nagalapuram', 'Narayanavanam', 'Pichatur',
            'Renigunta', 'Srikalahasti', 'Thottambedu', 'Venkatagiri', 'Yerpedu',
            'Buchinaidu Kandriga', 'Chittamur', 'Doravarisatram', 'Naidupeta', 'Ozili', 'Pellakuru',
            'Satyavedu', 'Sullurpeta', 'Tada', 'Vakadu', 'Varadaiahpalem',
            'Chandragiri', 'Chinnagottigallu', 'Chitvel', 'Kodur', 'Obulavaripalle', 'Pakala',
            'Penagalur', 'Pullampeta', 'Puttur', 'Ramachandrapuram', 'Tirupati Rural', 'Tirupati Urban',
            'Vadamalapeta', 'Yerravaripalem',
        ],
        'Visakhapatnam' => [
            'Anandapuram', 'Bheemunipatnam', 'Padmanabham', 'Seethammadhara', 'Visakhapatnam Rural',
            'Gajuwaka', 'Gopalapatnam', 'Maharanipeta', 'Mulagada', 'Pedagantyada', 'Pendurthi',
        ],
        'Vizianagaram' => [
            'Badangi', 'Bobbili', 'Dattirajeru', 'Gajapathinagaram', 'Mentada', 'Ramabhadrapuram',
            'Therlam',
            'Cheepurupalle', 'Garividi', 'Gurla', 'Merakamudidam', 'Rajam', 'Regidi Amadalavalasa',
            'Santhakaviti', 'Vangara',
            'Bhogapuram', 'Bondapalle', 'Denkada', 'Gantyada', 'Jami', 'Kothavalasa',
            'Lakkavarapukota', 'Nellimarla', 'Pusapatirega', 'Srungavarapukota', 'Vepada', 'Vizianagaram',
        ],
        'West Godavari' => [
            'Akividu', 'Bhimavaram', 'Kalla', 'Palacoderu', 'Undi', 'Veeravasaram',
            'Achanta', 'Mogalthur', 'Palakollu', 'Penugonda', 'Penumantra', 'Poduru', 'Yelamanchili',
            'Attili', 'Ganapavaram', 'Iragavaram', 'Pentapadu', 'Tadepalligudem', 'Tanuku',
        ],
        'YSR Kadapa' => [
            'Atlur', 'B. Kodur', 'Badvel', 'Brahmamgarimattam', 'Chapad', 'Duvvur', 'Gopavaram',
            'Kalasapadu', 'Khajipet', 'Porumamilla', 'S.Mydukur', 'Sri Avadhutha Kasinayana',
            'Jammalamadugu', 'Kondapuram', 'Muddanur', 'Mylavaram', 'Peddamudium', 'Proddatur',
            'Rajupalem',
            'Chennur', 'Chinthakommadinne', 'Kadapa', 'Kamalapuram', 'Pendlimarri', 'Sidhout',
            'Vallur', 'Vontimitta', 'Yerraguntla',
            'Chakrayapet', 'Lingala', 'Pulivendla', 'Simhadripuram', 'Thondur', 'Veerapunayunipalle',
            'Vempalle', 'Vemula',
            'Nandalur', 'Rajampet', 'T. Sundupalle', 'Veeraballi',
        ],
    ],
];
